apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: identity-service-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: travel-tvb-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: identity-service-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: travel-tvb/production/identity-service
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: catalog-service-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: travel-tvb-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: catalog-service-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: travel-tvb/production/catalog-service
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: booking-service-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: travel-tvb-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: booking-service-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: travel-tvb/production/booking-service
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: payment-service-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: travel-tvb-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: payment-service-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: travel-tvb/production/payment-service
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: content-service-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: travel-tvb-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: content-service-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: travel-tvb/production/content-service
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ai-chatbot-service-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: travel-tvb-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: ai-chatbot-service-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: travel-tvb/production/ai-chatbot-service
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rabbitmq-connection-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: travel-tvb-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: rabbitmq-connection-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: travel-tvb/production/rabbitmq
