apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - runtime-config.yaml
  - ai-chatbot-service.yaml
  - api-gateway.yaml
  - identity-service.yaml
  - catalog-service.yaml
  - booking-service.yaml
  - payment-service.yaml
  - content-service.yaml
  - hpa.yaml
  - ingress.yaml
