apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base
  - namespace.yaml
  - external-secrets.yaml

patches:
  - path: ingress-host.patch.yaml
  - path: payment-return-url.patch.yaml
