apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - elasticsearch.yaml
  - kibana.yaml
  - fluent-bit-rbac.yaml
  - fluent-bit-config.yaml
  - fluent-bit-daemonset.yaml
